Document: eliloader
Title: Debian eliloader Manual
Author: <insert document author here>
Abstract: This manual describes what eliloader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/eliloader/eliloader.sgml.gz

Format: postscript
Files: /usr/share/doc/eliloader/eliloader.ps.gz

Format: text
Files: /usr/share/doc/eliloader/eliloader.text.gz

Format: HTML
Index: /usr/share/doc/eliloader/html/index.html
Files: /usr/share/doc/eliloader/html/*.html
